config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts
  get 'index' =>'practice#index'
  post 'index' => 'practice#index'

  get 'about' => 'practice#about'

  root "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments
	belongs_to :user

	paginates_per 3
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  mount_uploader :avatar, AvatarUploader
         
	has_many :posts
	has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!


   before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	  def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

	    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
	  end

	end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
  	@name = params[:name]

  end

  def about
  	@color = params[:color]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  
  <div class="form-group">
    <%= f.hidden_field :post_id, value: @post.id %>
  </div>
  
  <div class="field">
    <%= f.text_area :comment_entry, placeholder: "Tell me something good...", class: "form-control" %>
  </div>
  <div class="form group">
    <%= f.submit "Tell the World", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spr17Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Begin Navbar -->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "All Posts", posts_path%></li> 
        <li>
          <% if user_signed_in? %>
           <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %> 
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% end %>
      </li>
      </ul>

      <h3 style="text-align: center;">Heather's Thoughts on Randomness...</h3>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- End Navbar -->


  <div class="container">
  <% if user_signed_in? %>
      <h3>Welcome <%= current_user.email %>!<%= image_tag current_user.avatar.thumb %></h3>
  <% end %>
	<%= yield %>
</div>	

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
   
    <%= f.text_field :title, placeholder: "Blog Entry Title", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= f.text_area :blog_entry, placeholder: "What's on your mind?", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "So it is said...", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thoughts...</h1>
  <div class="well" >
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Created At</th>
          <th>Blog entry</th>

          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
        
          <tr>
        
            <td><%= post.title %></td>
            <td><%= post.user.username %><%= image_tag post.user.avatar.thumb %></td>
            <td><%= post.created_at.strftime('%A, %B %d, %Y')%></td>
            <td><%= post.blog_entry.html_safe %></td>
            <td><%= link_to 'Show', post, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-primary" %></td>

          </tr>

        <% end %>
      </tbody>
    </table>
   </div>

<br>
<p><%= paginate @posts %></p>
<p><%= link_to 'New Post', new_post_path, class: "btn btn-primary" %></p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.user.username %><%= image_tag @post.user.avatar.thumb %>
</p>

<p>
  <strong>Created At:</strong>
  <%= @post.created_at.strftime('%A, %B %d, %Y') %>
</p>

<p>
  <strong>Blog entry:</strong>
  <%= @post.blog_entry.html_safe %>
</p>


<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %> |
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>


<div id="comments">

    <%= render 'comments/form', comment: @comment %>

</div>

<% @post.comments.each do |comment| %>
<div class="well">
    <p>On <%=comment.created_at.strftime("%A, %B %e  at %I:%M%p")%>, <%= image_tag comment.user.avatar.thumb, width: '50px', height: '50px' %><%= comment.author %> said...<br /> 
	    <%= comment.comment_entry %></p>
</div>
<% end %>

app/views/practice/about.html.erb
<style>
	#color_me_in {
		background-color: <%= @color %>;
		color: white;
		width: 250px;
		height: 250px;

	}
	</style>



<div id="color_me_in">
	<p>
	 <%= @color.upcase %> BOX ACTIVATED!

	</p>
</div>	


<%= form_tag index_path do %>

<p><%= text_field_tag :name, nil, placeholder: "What's your name?" %></p>

<p><%= submit_tag :submit %></p>

<% end %>

app/views/practice/index.html.erb
<h1>Chose a Color!</h1>


<% if !@name.nil? %>
	<h2>Welcome Back <%= @name %>!</h2>
<% end %>	

<p>
	<%= link_to "Red", about_path(color: "red") %>
</p>

<!-- This is saying the same thing as below: -->
<!-- <a href="http://localhost:3000/about" style="color: red"> Red</a> -->
<p>
    <%= link_to "Blue", about_path(color: "blue") %>
</p>

<p>
    <%= link_to "Green", about_path(color: "green") %>
</p>

<p>
    <%= link_to "Yellow", about_path(color: "yellow") %>
</p>